version: '3'
services:
  deploy:
    build:
      context: .
      dockerfile: publish.Dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: ./tasks/publish.sh
