version: '3'
services:
  build:
    image: node:12
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      NPM_TOKEN: ${NPM_TOKEN}
    command: ./tasks/build.sh
  deploy:
    image: node:12
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      NPM_TOKEN: ${NPM_TOKEN}
      CI: "true"
    command: ./tasks/deploy.sh