name: pipeline
on:
  push:
    branches:
      - master
      - beta
  workflow_dispatch:
    inputs:
      deploy:
        description: deploy
        required: true
        default: "true"
jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker-compose -f tasks/docker-compose.yml build build
          docker-compose -f tasks/docker-compose.yml run build
          docker-compose -f tasks/docker-compose.yml down
      - name: deploy
        env:
          DEPLOY: ${{ github.event.inputs.deploy }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker-compose -f tasks/docker-compose.yml build deploy
          docker-compose -f tasks/docker-compose.yml run deploy
          docker-compose -f tasks/docker-compose.yml down
