name: pipeline
on:
  push:
    branches:
      - master
      - beta
  workflow_dispatch:
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          docker-compose -f tasks/docker-compose.yml build build
          docker-compose -f tasks/docker-compose.yml run build
          docker-compose -f tasks/docker-compose.yml down
      - name: deploy
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          docker-compose -f tasks/docker-compose.yml build deploy
          docker-compose -f tasks/docker-compose.yml run deploy
          docker-compose -f tasks/docker-compose.yml down
